### ISSUE TITLE
Admin settings menu display problem - unusable

### ISSUE THREAD

**Issue by derekpa** [CitizensFoundation/open-active-democracy#4]
On the latest version of Master.

When you select the site settings option in the admin menu the extra options in the popup window appears, but then disappears immediately you remove the pointer from the menu link, so that the options window disappears before you have a chance to reach them with the pointer, making them unselectable.

Happens on current browsers: firefox 9.0.1, chrome 16.0.912.77 and Safari 5.1.2

Not sure yet whether you are using css or javascript for the drop down.

**Comment by rbjarnason** [comment]
We have just merge in a big 3 months worth of work into the master branch. Please try again.
